version: '3.8'
services:
  # postgres:
  #   image: kartoza/postgis:13.0
  #   container_name: postgres_postgis
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   env_file:
  #     - .env
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   networks:
  #     - api-network

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   restart: always
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis:/data
  #   networks: 
  #     - api-network
  build:
    build: .
    container_name: rental-api
    restart: always
    # environment:
    #   - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    # depends_on:
      # - postgres
      # - redis
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    networks:
      - api-network

# volumes:
  # postgres:
  #  name: postgres-volume
  # redis:
  #   driver: local

networks:
  api-network:


    