// import { Injectable } from '@nestjs/common';
// import { I18nService } from 'nestjs_i18n';

// @Injectable()
// export class EnumService {
//   constructor(private readonly i18n: I18nService) {}
// }
export enum GenderEnum {
    MALE = 'male',
    FEMALE = 'female',
    // NON_BINARY = 'non_binary',
    // PREFER_NOT_TO_SAY = 'prefer_not_to_say',
}

export enum RelationshipStatusEnum {
    SINGLE = 'single',
    MARRIED = 'married',
    DIVORCED = 'divorced',
    WIDOWED = 'widowed',
    SEPARATED = 'separated',
    ENGAGED = 'engaged',
    OPEN_RELATIONSHIP = 'open_relationship',
}

export enum FaithEnum {
    CHRISTIAN = 'christian',
    MUSLIM = 'muslim',
    HINDU = 'hindu',
    AFRICAN_TRADITIONAL = 'african_traditional',
    ATHEIST = 'atheist',
    NON_RELIGIOUS = 'non_religious',
    OTHER = 'other',
}

export enum EmploymentStatusEnum {
    EMPLOYED_FULL_TIME = 'employed_full_time',
    EMPLOYED_PART_TIME = 'employed_part_time',
    SELF_EMPLOYED = 'self_employed',
    UNEMPLOYED = 'unemployed',
    STUDENT = 'student',
    RETIRED = 'retired',
    HOMEMAKER = 'homemaker',
}

export enum ResidenceStatusEnum {
    CITIZEN = 'citizen',
    PERMANENT_RESIDENT = 'permanent_resident',
    TEMPORARY_RESIDENT = 'temporary_resident',
    WORK_VISA = 'work_visa',
    STUDENT_VISA = 'student_visa',
}

export enum InterestEnum {
    ART_AND_DESIGN = 'art_and_design',
    BOOKS_AND_WRITING = 'books_and_writing',
    COOKING_AND_FOOD = 'cooking_and_food',
    DANCING = 'dancing',
    FASHION_AND_STYLE = 'fashion_and_style',
    GAMING = 'gaming',
    MUSIC = 'music',
    MOVIES_AND_TV = 'movies_and_tv',
    OUTDOOR_ACTIVITIES = 'outdoor_activities',
    PHOTOGRAPHY = 'photography',
    SPORTS = 'sports',
    TRAVEL = 'travel',
    ANIME = 'anime',
    BOARD_GAMES = 'board_games',
    DIY_AND_CRAFTS = 'diy_and_crafts',
    GARDENING = 'gardening',
    HIKING = 'hiking',
    KNITTING = 'knitting',
    PAINTING = 'painting',
    READING = 'reading',
    VOLUNTEERING = 'volunteering',
    YOGA = 'yoga',
    TECHNOLOGY_AND_GADGETS = 'technology_and_gadgets',
    SCIENCE_AND_NATURE = 'science_and_nature',
    ANIMALS = 'animals',
    LANGUAGES = 'languages',
    PHILOSOPHY = 'philosophy',
    HISTORY = 'history',
    POLITICS = 'politics',
    I_AM_OPEN = 'i_am_open',
}

export enum FaithBasedMatchEnum {
    YES = 'yes',
    NO = 'no',
    MAYBE = 'maybe',
}

export enum ChildrenEnum {
    I_HAVE_CHILDREN = 'i_have_children',
    I_DONT_HAVE_CHILDREN = 'i_dont_have_children',
    I_DONT_WANT_CHILDREN = 'i_dont_want_children',
    I_WANT_CHILDREN = 'i_want_children',
    ITS_COMPLICATED = 'its_complicated',
    NO_PREFERENCE = 'no_preference',
}

export enum EducationalBackgroundEnum {
    BACHELORS = 'bachelors',
    COLLEGE = 'college',
    DOCTORATE = 'doctorate',
    POST_GRADUATE = 'post_graduate',
    HIGH_SCHOOL = 'high_school',
    SKILL_CERTIFICATE = 'skill_certification',
    NO_DIPLOMA = 'no_diploma',
}

export enum LifestyleEnum {
    HEALTHY_EATING = 'healthy_eating',
    REGULAR_EXERCISE = 'regular_exercise',
    SUFFICIENT_SLEEP = 'sufficient_sleep',
    NO_SMOKING = 'no_smoking',
    STRESS_MANAGEMENT = 'stress_management',
    ALCOHOL_IN_MODERATION = 'alcohol_in_moderation',
    MEDICAL_CHECKUPS = 'medical_checkups',
    VACCINATIONS = 'vaccinations',
    HYDRATION = 'hydration',
    VEGETARIAN = 'vegetarian',
    VEGAN = 'Vegan',
    GLUTEN_FREE = 'gluten_free',
    LOW_CARB = 'low_carb',
    INTERMITTENT_FASTING = 'intermittent_fasting',
    YOGA = 'yoga',
    PILATES = 'pilates',
    RUNNING = 'running',
    CYCLING = 'cycling',
    SWIMMING = 'swimming',
    WEIGHT_TRAINING = 'weight_training',
    MENTAL_HEALTH = 'mental_health',
    PERSONAL_CARE = 'personal_care',
    SKIN_CARE = 'skin_care',
    ENVIROMENTAL_CONSCIOUSNESS = 'environmental_consciousness',
    COMMUNITY_INVOLVEMENT = 'community_involvement',
    NO_ALCOHOL = 'no_alcohol',
}

export enum RelationshipGoalsEnum {
    CASUAL_DATING = 'casual_dating',
    SERIOUS_RELATIONSHIP = 'serious_relationship',
    MARRIAGE = 'marriage',
}

export enum PersonalityTraitEnum {
    KIND_AND_COMPASSIONATE = 'kind_and_compassionate',
    HONEST_AND_TRUSTWORTHY = 'honest_and_trustworthy',
    LOYAL_AND_COMMITTED = 'loyal_and_committed',
    FUNNY_AND_HUMOROUS = 'funny_and_humorous',
    INTELLIGENT_AND_CURIOUS = 'intelligent_and_curious',
    ADVENTUROUS_AND_SPONTANEOUS = 'adventurous_and_spontaneous',
    PATIENT_AND_UNDERSTANDING = 'patient_and_understanding',
    OPTIMISTIC_AND_POSITIVE = 'optimistic_and_positive',
    GENEROUS_AND_THOUGHTFUL = 'generous_and_thoughtful',
    CREATIVE_AND_ARTISTIC = 'creative_and_artistic',
    INDEPENDENT_AND_SELF_SUFFICIENT = 'independent_and_self_sufficient',
    AMBITIOUS_AND_DRIVEN = 'ambitious_and_driven',
    EASYGOING_AND_LAIDBACK = 'easygoing_and_laidback',
    OUTGOING_AND_SOCIAL = 'outgoing_and_social',
    INTROVERTED_AND_THOUGHTFUL = 'introverted_and_thoughtful',
    ROMANTIC_AND_SENTIMENTAL = 'romantic_and_sentimental',
    SPIRITUAL_AND_FAITHFUL = 'spiritual_and_faithful',
}

export enum CulturalValuesEnum {
    FAMILY = 'Family',
    RELIGION = 'Religion',
    TRADITION = 'Tradition',
    LANGUAGE = 'Language',
    FOOD = 'Food',
    HOLIDAYS = 'Holidays',
    CLOTHING = 'Clothing',
}

export enum LanguagesEnum {
    Amharic = "Amharic",
    Arabic = "Arabic",
    Bashkir = "Bashkir",
    Bengali = "Bengali",
    Berber = "Berber",
    Bulgarian = "Bulgarian",
    Chichewa = "Chichewa",
    Croatian = "Croatian",
    Czech = "Czech",
    Danish = "Danish",
    Dholuo = "Dholuo",
    Dutch = "Dutch",
    English = "English",
    Estonian = "Estonian",
    Ewe = "Ewe",
    Finnish = "Finnish",
    French = "French",
    Fula = "Fula",
    German = "German",
    Greek = "Greek",
    Hausa = "Hausa",
    Hebrew = "Hebrew",  
    Hindi = "Hindi",
    Hungarian = "Hungarian",
    Igbo = "Igbo",
    Indonesian = "Indonesian",
    Italian = "Italian",
    Japanese = "Japanese",
    Kinyarwanda = "Kinyarwanda",
    Kirundi = "Kirundi",
    Korean = "Korean",
    Latvian = "Latvian",
    Lithuanian = "Lithuanian",
    Maasai = "Maasai",
    Malagasy = "Malagasy",
    Malay = "Malay",
    MandarinChinese = "Mandarin_chinese",
    Mandingo = "Mandingo",
    Marathi = "Marathi",
    Ndebele = "Ndebele",
    Norwegian = "Norwegian",
    Oromo = "Oromo",
    Persian = "Persian_farsi",
    Polish = "Polish",
    Portuguese = "Portuguese",
    Punjabi = "Punjabi",
    Romanian = "Romanian",
    Russian = "Russian",
    Serbian = "Serbian",
    Shona = "Shona",
    Slovak = "Slovak",
    Somali = "Somali",
    Spanish = "Spanish",
    Swahili = "Swahili",
    Swedish = "Swedish",
    Tamil = "Tamil",
    Telugu = "Telugu",
    Thai = "Thai",
    Turkish = "Turkish",
    Ukrainian = "Ukrainian",
    Urdu = "Urdu",
    Vietnamese = "Vietnamese",
    Xhosa = "Xhosa",
    Yoruba = "Yoruba",
    Zulu = "Zulu",
  }
  
export enum FinancialViewEnum {
    VERY_IMPORTANT = 'very_important',
    IMPORTANT = 'important',
    SOMEWHAT_IMPORTANT = 'somewhat_important',
    NOT_IMPORTANT = 'not_important',
    STILL_FIGURING = 'still_figuring'
}

export enum LocationEnum {
    AUSTRALIA = 'Australia',
    CANADA = 'Canada',
    FRANCE = 'France',
    GERMANY = 'Germany',
    ITALY = 'Italy',
    NEW_ZEALAND = 'new_zealand',
    SPAIN = 'Spain',
    UNITED_KINGDOM = 'United_Kingdom',
    UNITED_STATES = 'United_States',
}

export enum ProfessionEnum {
    ACCOUNTANT = "accountant",
    ACTOR = "actor",
    ADMINISTRATION_PROFESSIONAL = "administration_professional",
    ADVERTISING_PROFESSIONAL = "advertising_professional",
    ARCHITECT = "architect",
    ARTIST = "artist",
    BAKER = "baker",
    BANKER = "banker",
    BARTENDER = "bartender",
    BIOLOGIST = "biologist",
    BUSINESS_ANALYST = "business_analyst",
    CARPENTER = "carpenter",
    CHEF = "chef",
    CHEMICAL_ENGINEER = "chemical_engineer",
    CIVIL_ENGINEER = "civil_engineer",
    COMPUTER_SCIENTIST = "computer_scientist",
    CONSULTANT = "consultant",
    DATA_ANALYST = "data_analyst",
    DENTIST = "dentist",
    DOCTOR = "doctor",
    ECONOMIST = "economist",
    ELECTRICIAN = "electrician",
    ENGINEER = "engineer",
    ENTREPRENEUR = "entrepreneur",
    FARMER = "farmer",
    FINANCIAL_ANALYST = "financial_analyst",
    FIREFIGHTER = "firefighter",
    FLIGHT_ATTENDANT = "flight_attendant",
    GRAPHIC_DESIGNER = "graphic_designer",
    HUMAN_RESOURCES_SPECIALIST = "human_resources_specialist",
    IT_SPECIALIST = "it_specialist",
    JOURNALIST = "journalist",
    JUDGE = "judge",
    LAWYER = "lawyer",
    LIBRARIAN = "librarian",
    MACHINIST = "machinist",
    MARKETING_SPECIALIST = "marketing_specialist",
    MATHEMATICIAN = "mathematician",
    MECHANIC = "mechanic",
    MEDICAL_PROFESSIONAL_FIELDS = "medical_professional_fields",
    MILITARY_OFFICER = "military_officer",
    NURSE = "nurse",
    OTHERS = "others",
    PARAMEDIC = "paramedic",
    PHARMACIST = "pharmacist",
    PHOTOGRAPHER = "photographer",
    PILOT = "pilot",
    PLUMBER = "plumber",
    POLICE_OFFICER = "police_officer",
    PROFESSOR = "professor",
    PROJECT_MANAGER = "project_manager",
    PSYCHOLOGIST = "psychologist",
    RECEPTIONIST = "receptionist",
    REAL_ESTATE_PROFESSIONAL = "real_estate_professional",
    RELIGIOUS_LEADER = "religious_leader",
    RESEARCHER = "researcher",
    RETIRED = "retired",
    SALES_PROFESSIONAL = "sales_professional",
    SCIENTIST = "scientist",
    SOCIAL_WORKER = "social_worker",
    SOCIAL_MEDIA_INFLUENCER = "social_media_influencer",
    SOFTWARE_DEVELOPER = "software_developer",
    SOLDIER = "soldier",
    SPORTSMAN = "sportsman",
    STUDENT = "student",
    SUPPORT_WORKER = "support_worker",
    TEACHER = "teacher",
    THERAPIST = "therapist",
    TRANSLATOR = "translator",
    TRANSPORTATION_SPECIALIST = "transportation_specialist",
    UNEMPLOYED = "unemployed",
    VETERINARIAN = "veterinarian",
    WEB_DEVELOPER = "web_developer",
    WRITER = "writer",
    ZOOLOGIST = "zoologist"
  }
  